### ISSUE TITLE
Crash on Android "ForegroundServiceDidNotStartInTimeException"

### ISSUE THREAD

**Issue by pbouttier** [gdelataillade/alarm#230]
**Alarm plugin version**
3.1.5

**Describe the bug**
Play Store and Sentry report the same bug, a crash 

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b388286 u0 com.pbouttier.sptraining/com.gdelataillade.alarm.alarm.AlarmService}
    at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2261)
    at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2232)
    at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2526)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:222)
    at android.os.Looper.loop(Looper.java:314)
    at android.app.ActivityThread.main(ActivityThread.java:8602)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
```

**To Reproduce**
*Steps to reproduce the behavior:*
I didn't reproduce it myself, I only have the data from the play store, from sentry

**Expected behavior**
No crash :)

**Screenshots**
I didn't reproduce it myself

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
Happen mostly on Android 14, but also and 13, 12, 10. And on multiple devices : samsung, xiaomi, redmi ...

**Additional context**
I have the "await" on most of my functions.

How i have set the alarm 

```
  Future<void> setAlarm(DateTime dateTime) async {
    UserSettingsModel userSettings = await ref.read(userSettingsProvider.future);

    final alarmSettings = AlarmSettings(
      id: alarmId,
      dateTime: dateTime,
      assetAudioPath: 'assets/audio/alarm.mp3',
      loopAudio: false,
      vibrate: userSettings.noticeEndCountdown == NoticeEndCountdown.vibrate,
      // Le son est indépendant du son configuré à l'instant T sur Android, ça le remet brieffement à cette valeur
      volume: userSettings.noticeEndCountdown == NoticeEndCountdown.sound ? userSettings.countdownVolume : 0.0, 
      notificationTitle: tr('workout.ongoing.notification_countdown.title'),
      notificationBody: tr('workout.ongoing.notification_countdown.body'),
      enableNotificationOnKill: false,
      androidFullScreenIntent: false,
    );
    await Alarm.set(alarmSettings: alarmSettings);
  }
```
I didn't have await on the `stop`, I'll add it in the next version of my app, just in case. 

Thanks for your time, this bug apart from the package is great :)

**Comment by pbouttier** [comment]
I've tried the `4.0.0-dev.1` : 

I need to add `-keep class com.gdelataillade.alarm.models.** { *; }` to `proguard-rules.pro`. Otherwise in `--release` i got this error 

`See https://github.com/google/gson/blob/main/Troubleshooting.md#r8-abstract-class, null, java.lang.RuntimeException: AlarmSettings Error parsing JSON to AlarmSettings: Abstract classes can't be instantiated! Adjust the R8 configuration or register an InstanceCreator or a TypeAdapter for this type. Class name: h0.b`

in `models/AlarmSettings.kt`

```
val gson = Gson()
val jsonString = gson.toJson(modifiedJson)
val result = gson.fromJson(jsonString, AlarmSettings::class.java)
```
And I've seen other minor things. I don't know if it's directly related to 4.0.0, or to the scope you wanted to integrate, but I'll put them here anyway just in case: 

- When the alarm sounds, the icon of my app is shown in the taskbar at the top, but in the notification itself only a white square is present.

- When I set an alarm 5s later, and kill the app, it's not triggered. If I don't kill the app, it shows up fine. If I set an alarm 10s later, and kill the app, it will be triggered. If the time is too short, it doesn't seem to set, perhaps a problem with the exact time?

**Comment by gdelataillade** [comment]
Hi @pbouttier 

Thanks for your feedback !

1) About the error parsing JSON to `AlarmSettings`, I added the `proguard-rules.pro` to the plugin and released version [4.0.0-dev.2](https://pub.dev/packages/alarm/versions/4.0.0-dev.2).

2) About the notification icon, I should indeed do something so developers can customize it. I'll add it to my to do list.

3) This behavior occurs because, for alarms set to trigger within 5 seconds or less, I bypass the `AlarmManager` and directly start the `AlarmService`. The reason for this is that triggering the `AlarmManager` is a resource-intensive operation that can take a few seconds to execute, which is impractical for such short intervals. However, I can optimize this by reducing the threshold from 5 seconds to 3 seconds.

**Comment by pbouttier** [comment]
Nice !

For 3, I don't think it's necessary to do anything specific. I was testing it in brute force mode, but it's unlikely to have a real case where it needs to alarm less than 5s later.

**Comment by pbouttier** [comment]
Re,

The problem persist on lastest version 

```
Exception android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException:
  at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException (ActivityThread.java:2262)
  at android.app.ActivityThread.throwRemoteServiceException (ActivityThread.java:2233)
  at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2527)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:222)
  at android.os.Looper.loop (Looper.java:314)
  at android.app.ActivityThread.main (ActivityThread.java:8610)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:565)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1081)
```

And a second one (few cases) : 

```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:5071)
  at android.app.ActivityThread.-$$Nest$mhandleServiceArgs
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2435)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:224)
  at android.os.Looper.loop (Looper.java:318)
  at android.app.ActivityThread.main (ActivityThread.java:8762)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:561)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1013)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
  at org.json.JSONTokener.nextCleanInternal (JSONTokener.java:121)
  at org.json.JSONTokener.nextValue (JSONTokener.java:98)
  at org.json.JSONObject.<init> (JSONObject.java:168)
  at org.json.JSONObject.<init> (JSONObject.java:185)
  at com.gdelataillade.alarm.alarm.AlarmService.onStartCommand (AlarmService.kt:71)
  at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:5053)
```

**Comment by gdelataillade** [comment]
Hi @pbouttier 

I've been unable to reproduce your issue. Are you sure you followed the installation steps ?

**Comment by pbouttier** [comment]
Re, sorry for my late reply.

I was missing the scheduleExactAlarm permission but I can't find a configuration where it would be disabled, nor can I reproduce the problem on an emulator.

My hope was that you had an idea of what might be blocking it, but if we're both lost, we'll be sailing blind.

Maybe something like this ? https://stackoverflow.com/questions/77415459/android-13-foregroundservicedidnotstartintimeexception, https://github.com/androidx/media/issues/112 ?

**Comment by gdelataillade** [comment]
I'm aware of the 5 seconds rule, I run `startForeground` almost instantly when alarm is triggered. Maybe there's an error before it is called. Do you have more logs to share ?

**Comment by pbouttier** [comment]
I have these json from sentry. Android 13 & 14, differents permissions. 

[schedule, post notif not granted us.sentry.io.json](https://github.com/user-attachments/files/17094508/schedule.post.notif.not.granted.us.sentry.io.json)
[playback not granted us.sentry.io.json](https://github.com/user-attachments/files/17094509/playback.not.granted.us.sentry.io.json)

**Comment by gdelataillade** [comment]
Hi @pbouttier 

Sorry for the late reply. Do you ask for the `scheduleExactAlarm` permission ? If we can't reproduce the issue maybe it's because this permission is not granted by default in some devices. Maybe you could try to add it (see [doc step 5](https://github.com/gdelataillade/alarm/blob/main/help/INSTALL-ANDROID.md)) and see if the issue still appears in your Sentry.

What do you think ?

**Comment by pbouttier** [comment]
In the second error log (sorry, I only saw afterwards that it was a raw file, with no indentation or line feeds), the permissions were : 

```
‘SCHEDULE_EXACT_ALARM": “granted”,
‘USE_EXACT_ALARM": “granted”,
```

So the problem must not be there

**Comment by gdelataillade** [comment]
I saw something interesting in the second error log:

```json
"FOREGROUND_SERVICE_MEDIA_PLAYBACK": "not_granted"
```

I believe this permission is necessary. The weird thing is that it should be granted by default when I added it in the plugin's manifest [here](https://github.com/gdelataillade/alarm/blob/main/android/src/main/AndroidManifest.xml):
```xml
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK"/>
```

Did you disable it manually ? Does you other logs have this permission not granted ?

If so, log 1 may crash because of `SCHEDULE_EXACT_ALARM` and log 2 because of `FOREGROUND_SERVICE_MEDIA_PLAYBACK`. What do you think ?

**Comment by pbouttier** [comment]
Sorry for my late reply.

I haven't had time to test the request for the SCHEDULE_EXACT_ALARM permission. I'll include it in my next update but it's a big one, I've still got other points to finish. 

I don't understand FOREGROUND_SERVICE_MEDIA_PLAYBACK either. The permission is in the .xml file, so it ‘should work’.

**Comment by gdelataillade** [comment]
No problem. Let me know how it goes in your next update !

**Comment by synstin** [comment]
I often report the same crash.

```
POCO peridot (POCO F6) - Android 14(SDK 34)

android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException
Exception android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException:
  at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException (ActivityThread.java:2250)
  at android.app.ActivityThread.throwRemoteServiceException (ActivityThread.java:2221)
  at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2515)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:224)
  at android.os.Looper.loop (Looper.java:318)
  at android.app.ActivityThread.main (ActivityThread.java:8790)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:561)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1013)

```

**Comment by synstin** [comment]
I've set all four permissions. This is my current list of permissions. Thank you.
```
<!-- PERMISSION -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="28"/>
    <!-- /PERMISSION -->

    <!-- ALARM -->
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK"/>
    <!-- /ALARM -->

    <!-- AWESOME NOTIFICATION PERMISSION -->
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY"/>
    <!-- /AWESOME NOTIFICATION PERMISSION -->
```

**Comment by riqtech90** [comment]
<img width="1262" alt="Screenshot 2024-11-10 at 8 16 35 PM" src="https://github.com/user-attachments/assets/96551f3f-8784-4588-b004-855efed81017">

My app also received daily crash report from firebase crashlytic. Haven't experience the crash personally, but from what i see, the crash report most of it is android 8 to android 11 devices

**Comment by pbouttier** [comment]
I have included the permission, the crashes are always present at the same frequency.

Additional information : 
- 95% of my crashes have been on xiaomi, with MUI. Apparently they have harder management of background tasks.
- 74% of problems appear in the background
- 100% have a proximity sensor activated (crashlytics tells me this, I don't see the logic, but ...)
- the Android version doesn't seem to change anything

I saw that you were releasing a 5.0.0 with ‘more efficient’, is there any chance that will help?

Thanks again for your work

**Comment by gdelataillade** [comment]
This issue seems to be related to MIUI’s customizations rather than Android itself, since it’s reported across multiple Android versions. The ForegroundServiceDidNotStartInTimeException happens because MIUI likely delays or kills the AlarmService when it tries to start, even if it’s implemented correctly. As for the proximity sensor correlation, it might just be a coincidence tracked by Crashlytics, but it’s possible MIUI applies stricter background restrictions when the sensor is active (like when the phone is in a pocket or face down).

The best workaround for now is to guide Xiaomi users to disable battery optimization for your app in their settings. You can redirect them to the specific system screen where they can whitelist your app to prevent MIUI from interfering with the service. Let me know if you need help implementing this!

Finally, I don't think `5.0.0` will fix this kind of crash, but you can still try it, we never know:
`alarm: ^5.0.0-dev.8`
