### ISSUE TITLE
v4.0.3 bugs

### ISSUE THREAD

**Issue by aykutuludag** [gdelataillade/alarm#251]
**Alarm plugin version**
*v4.0.3*

**Describe the bug**
*Bugs from crashlytics*

**Additional context**
*Until now, no iOS crash detected.* For Android bugs, please see below:

**JsonReader.unexpectedTokenError**

```
Fatal Exception: java.lang.RuntimeException: Unable to start service com.gdelataillade.alarm.alarm.AlarmService@1ec0e222 with Intent { cmp=APP.PACKAGE.NAME/com.gdelataillade.alarm.alarm.AlarmService (has extras) }: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 108 path $.stopButton
See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3975)
       at android.app.ActivityThread.access$2300(ActivityThread.java:218)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1842)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:7007)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

Apperantly, this issue only happening on older Android versions.

![image](https://github.com/user-attachments/assets/5bec1e4e-bf20-4ccd-b8c1-b88b1c9b9db1)

If any more issues occur, I will write here. Best regards.

**Comment by aykutuludag** [comment]
I applied v4.0.4. Apperantly crash reports seems to be gone. Have a nice day.
