### ISSUE TITLE
Android native crash on v4.1.1

### ISSUE THREAD

**Issue by aykutuludag** [gdelataillade/alarm#305]
I am getting following errors on many devices.

```
          Fatal Exception: java.lang.RuntimeException: Unable to start service com.gdelataillade.alarm.alarm.AlarmService@86ff602 with Intent { cmp=app.packagename/com.gdelataillade.alarm.alarm.AlarmService (has extras) }: java.lang.NullPointerException: notificationSettings must not be null
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3694)
       at android.app.ActivityThread.-wrap21()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

My code:

```
Future<void> createAlarm(
    int alarmId, DateTime dateTime, String title, String body) async {
  final alarmSettings = AlarmSettings(
      id: alarmId,
      dateTime: dateTime,
      assetAudioPath: 'assets/sounds/notification.mp3',
      loopAudio: false,
      vibrate: true,
      volume: 1,
      androidFullScreenIntent: false,
      warningNotificationOnKill: false,
      notificationSettings: NotificationSettings(
        title: title,
        body: body,
      ));
  await Alarm.set(alarmSettings: alarmSettings);
}
```

![image](https://github.com/user-attachments/assets/1991601f-fa77-4a71-8e95-996a9bfd90f6)

**Comment by gdelataillade** [comment]
Hi @aykutuludag 

Did you upgrade the alarm package from `3.x.x` to `4.1.1` ?

**Comment by aykutuludag** [comment]
No. This error happened after I upgraded from 4.0.6 to 4.1.1

**Comment by gdelataillade** [comment]
Hi @aykutuludag 

I just released version `5.0.0`. Please let me know if it fixes this issue.

**Comment by aykutuludag** [comment]
I just updated to v5.0.1. I am writing the bugs.
