### ISSUE TITLE
Error on startup after update source code to Flutter 3.10

### ISSUE THREAD

**Issue by romarito** [gdelataillade/alarm#56]
**Alarm plugin version**
1.1.2

**Describe the bug**
My app stopped working after I updated the source code to Flutter 3.10 because it crashes on Alarm startup:

Syncing files to device SM G925I...
I/FlutterBackgroundExecutor(25293): Starting AlarmService...
I/AndroidAlarmManagerPlugin(25293): onAttachedToEngine
E/flutter (25293): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Stop alarm error: Null check operator used on a null value
E/flutter (25293): #0      AndroidAlarm.stop (package:alarm/src/android_alarm.dart:236:7)
E/flutter (25293): #1      Alarm.stop (package:alarm/alarm.dart:155:68)
E/flutter (25293): <asynchronous suspension>
E/flutter (25293): #2      Alarm.set (package:alarm/alarm.dart:75:9)
E/flutter (25293): <asynchronous suspension>
E/flutter (25293): #3      Alarm.checkAlarm (package:alarm/alarm.dart:55:9)
E/flutter (25293): <asynchronous suspension>
E/flutter (25293): #4      Alarm.init (package:alarm/alarm.dart:44:5)
E/flutter (25293): <asynchronous suspension>
E/flutter (25293): #5      main (package:adm_firula/main.dart:24:3)
E/flutter (25293): <asynchronous suspension>
E/flutter (25293): 
I/flutter (25293): [Alarm] Notification with id 1006576 canceled
I/AlarmService(25293): AlarmService started!

This line in main.dart is where the "await Alarm.init" is. It seems to me that Alarm is trying to execute tasks before AlarmService has completed its initialization, isn't it?

If I delete the Alarm package the app loads normally. If I return the package and delete the app from the device, the application loads normally upon installation and activates all programmed alarms, but it freezes when changing the screen and does not open again.

I run the tests directly on the device

**Device info**
Samsung S6, Android 7

**Comment by gdelataillade** [comment]
Hi @romarito,

It looks like something is wrong with the plugin new version `1.1.2` I released a couple days ago. I added custom exceptions to the plugin, but I looks like an exception is thrown when the service initializes and an alarm was previously scheduled, which is wrong.

I'll fix this as soon as possible. I'll let you know when it's done.

**Comment by gdelataillade** [comment]
Hi again @romarito,

I just made the quick fix and updated the plugin to `1.1.3`.

Please update it in your project and let me know if it works now as expected.

**Comment by romarito** [comment]
Thanks for the agility.

The app loaded ok but the alarms didn't:

E/flutter ( 2292): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'prefs' has not been initialized.
E/flutter ( 2292): #0      AlarmStorage.prefs (package:alarm/service/storage.dart)
E/flutter ( 2292): #1      AlarmStorage.getSavedAlarms (package:alarm/service/storage.dart:43:18)
E/flutter ( 2292): #2      Alarm.getAlarms (package:alarm/alarm.dart:176:58)
E/flutter ( 2292): #3      Alarm.set (package:alarm/alarm.dart:70:31)
E/flutter ( 2292): #4      _CardAgendaState._ativarAlarme (package:adm_firula/pages/calendario/card_agenda.dart:38:19)
E/flutter ( 2292): #5      _CardAgendaState.initState (package:adm_firula/pages/calendario/card_agenda.dart:46:7)
E/flutter ( 2292): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5219:55)
E/flutter ( 2292): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter ( 2292): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter ( 2292): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter ( 2292): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6435:14)
E/flutter ( 2292): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter ( 2292): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter ( 2292): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6435:14)
E/flutter ( 2292): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter ( 2292): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter ( 2292): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
E/flutter ( 2292): #17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
E/flutter ( 2292): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
E/flutter ( 2292): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
E/flutter ( 2292): #20     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5242:11)
E/flutter ( 2292): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter ( 2292): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter ( 2292): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter ( 2292): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
E/flutter ( 2292): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
E/flutter ( 2292): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
E/flutter ( 2292): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter ( 2292): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter ( 2292): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter ( 2292): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
E/flutter ( 2292): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
E/flutter ( 2292): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
E/flutter ( 2292): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter ( 2292): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter ( 2292): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter ( 2292): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
E/flutter ( 2292): #37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
E/flutter ( 2292): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
E/flutter ( 2292): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
E/flutter ( 2292): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5242:11)
E/flutter ( 2292): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter ( 2292): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter ( 2292): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter ( 2292): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
E/flutter ( 2292): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
E/flutter ( 2292): #46     ComponentElement._firstBuild (package:flutter/src/widge

**Comment by romarito** [comment]
I don't know if it's clear, but the plugin is still not working, SharedPreferences is not being initialized in "service/storage" and then the Alarm does not work.

**Comment by gdelataillade** [comment]
Everything looks fine on the plugin...

I found this answer in StackOverflow:
https://stackoverflow.com/questions/71065727/lateinitializationerror-sharedpreferences

Make sure you call `WidgetsFlutterBinding.ensureInitialized()` and then `Alarm.init` in your `main` function. This is how I did in the example app:

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  await Alarm.init(showDebugLogs: true);

  runApp(const MaterialApp(home: ExampleAlarmHomeScreen()));
}
```

Let me know if it works.

**Comment by gdelataillade** [comment]
Hi @romarito,

Sorry this error is my mistake. Please update the package to `1.1.5`, it should fix it !

Thank you for your time.
